window.PRODUCTS = [
  /* ============================
     CPU — Процесори (10)
  ============================ */
  {
    id: "cpu-5600x",
    title: "AMD Ryzen 5 5600X",
    category: "cpu",
    price: 5999,
    rating: 4.8,
    sku: "100-100000065BOX",
    img: "",
    desc: "6 ядер / 12 потоків • 3.7–4.6 ГГц • для ігор і роботи.",
    specs: { "Сокет": "AM4", "TDP": "65W", "Кеш L3": "32MB", "Техпроцес": "7nm" },
    buy: "#"
  },
  {
    id: "cpu-5600",
    title: "AMD Ryzen 5 5600",
    category: "cpu",
    price: 4999,
    rating: 4.7,
    sku: "100-100000927BOX",
    img: "https://picsum.photos/seed/cpu5600/800/600",
    desc: "6C/12T, 3.5–4.4 ГГц • оптимум для бюджетного геймінгу.",
    specs: { "Сокет": "AM4", "TDP": "65W", "Кеш L3": "32MB" },
    buy: "#"
  },
  {
    id: "cpu-5700x",
    title: "AMD Ryzen 7 5700X",
    category: "cpu",
    price: 7999,
    rating: 4.7,
    sku: "100-100000926WOF",
    img: "https://picsum.photos/seed/cpu5700x/800/600",
    desc: "8C/16T, 3.4–4.6 ГГц • універсальний восьмиядерник.",
    specs: { "Сокет": "AM4", "TDP": "65W", "Кеш L3": "32MB" },
    buy: "#"
  },
  {
    id: "cpu-5800x3d",
    title: "AMD Ryzen 7 5800X3D",
    category: "cpu",
    price: 11999,
    rating: 4.9,
    sku: "100-100000651WOF",
    img: "https://picsum.photos/seed/cpu5800x3d/800/600",
    desc: "3D V-Cache • топ для ігор на платформі AM4.",
    specs: { "Сокет": "AM4", "TDP": "105W", "Кеш L3": "96MB" },
    buy: "#"
  },
  {
    id: "cpu-7600",
    title: "AMD Ryzen 5 7600",
    category: "cpu",
    price: 7799,
    rating: 4.6,
    sku: "100-100001015BOX",
    img: "https://picsum.photos/seed/cpu7600/800/600",
    desc: "6C/12T, Zen 4 • висока продуктивність у 1080p/1440p.",
    specs: { "Сокет": "AM5", "TDP": "65W", "Памʼять": "DDR5" },
    buy: "#"
  },
  {
    id: "cpu-7700",
    title: "AMD Ryzen 7 7700",
    category: "cpu",
    price: 11499,
    rating: 4.7,
    sku: "100-100001590BOX",
    img: "https://picsum.photos/seed/cpu7700/800/600",
    desc: "8C/16T, Zen 4 • для стрімінгу й важких задач.",
    specs: { "Сокет": "AM5", "TDP": "65W", "Памʼять": "DDR5" },
    buy: "#"
  },
  {
    id: "cpu-12400f",
    title: "Intel Core i5-12400F",
    category: "cpu",
    price: 5650,
    rating: 4.8,
    sku: "BX8071512400F",
    img: "https://picsum.photos/seed/cpu12400f/800/600",
    desc: "6P/12T • відмінний баланс ціни та FPS.",
    specs: { "Сокет": "LGA1700", "TDP": "65W", "Памʼять": "DDR4/DDR5" },
    buy: "#"
  },
  {
    id: "cpu-13400f",
    title: "Intel Core i5-13400F",
    category: "cpu",
    price: 7999,
    rating: 4.7,
    sku: "BX8071513400F",
    img: "https://picsum.photos/seed/cpu13400f/800/600",
    desc: "10 ядер (6P+4E), 16 потоків • універсальний середній клас.",
    specs: { "Сокет": "LGA1700", "TDP": "65W", "Памʼять": "DDR4/DDR5" },
    buy: "#"
  },
  {
    id: "cpu-12600kf",
    title: "Intel Core i5-12600KF",
    category: "cpu",
    price: 7799,
    rating: 4.6,
    sku: "BX8071512600KF",
    img: "https://picsum.photos/seed/cpu12600kf/800/600",
    desc: "P+E архітектура • високі частоти, без iGPU.",
    specs: { "Сокет": "LGA1700", "TDP": "125W", "Памʼять": "DDR4/DDR5" },
    buy: "#"
  },
  {
    id: "cpu-13700f",
    title: "Intel Core i7-13700F",
    category: "cpu",
    price: 13999,
    rating: 4.7,
    sku: "BX8071513700F",
    img: "https://picsum.photos/seed/cpu13700f/800/600",
    desc: "16 ядер (8P+8E), 24 потоки • для важких задач і ігор.",
    specs: { "Сокет": "LGA1700", "TDP": "65W", "Памʼять": "DDR4/DDR5" },
    buy: "#"
  },

  /* ============================
     GPU — Відеокарти (10)
  ============================ */
  {
    id: "gpu-rtx4060-giga",
    title: "GeForce RTX 4060 8GB (різні бренди)",
    category: "gpu",
    price: 14999,
    rating: 4.6,
    sku: "RTX4060-8G",
    img: "https://picsum.photos/seed/gpu4060a/800/600",
    desc: "Ada Lovelace • DLSS 3 • ідеально для 1080p high/ultra.",
    specs: { "Памʼять": "8GB GDDR6", "TBP": "≈115W", "Виходи": "HDMI 2.1, DP 1.4a" },
    buy: "#"
  },
  {
    id: "gpu-rtx4060ti",
    title: "GeForce RTX 4060 Ti 8GB",
    category: "gpu",
    price: 21999,
    rating: 4.5,
    sku: "RTX4060Ti-8G",
    img: "https://picsum.photos/seed/gpu4060ti/800/600",
    desc: "Більше ядер і кешу, DLSS 3 • 1080p/1440p.",
    specs: { "Памʼять": "8GB GDDR6", "TBP": "≈160W" },
    buy: "#"
  },
  {
    id: "gpu-rtx4070",
    title: "GeForce RTX 4070 12GB",
    category: "gpu",
    price: 28999,
    rating: 4.7,
    sku: "RTX4070-12G",
    img: "https://picsum.photos/seed/gpu4070/800/600",
    desc: "1440p ультра з DLSS 3 • енергоефективна.",
    specs: { "Памʼять": "12GB GDDR6X", "TBP": "≈200W" },
    buy: "#"
  },
  {
    id: "gpu-rx6600",
    title: "Radeon RX 6600 8GB",
    category: "gpu",
    price: 8999,
    rating: 4.6,
    sku: "RX6600-8G",
    img: "https://picsum.photos/seed/gpu6600/800/600",
    desc: "Краще співвідношення ціна/FPS для 1080p.",
    specs: { "Памʼять": "8GB GDDR6", "TBP": "≈132W" },
    buy: "#"
  },
  {
    id: "gpu-rx6700xt",
    title: "Radeon RX 6700 XT 12GB",
    category: "gpu",
    price: 14999,
    rating: 4.6,
    sku: "RX6700XT-12G",
    img: "https://picsum.photos/seed/gpu6700xt/800/600",
    desc: "Сильна карта для 1440p без трасування.",
    specs: { "Памʼять": "12GB GDDR6", "TBP": "≈230W" },
    buy: "#"
  },
  {
    id: "gpu-rx7800xt",
    title: "Radeon RX 7800 XT 16GB",
    category: "gpu",
    price: 28999,
    rating: 4.7,
    sku: "RX7800XT-16G",
    img: "https://picsum.photos/seed/gpu7800xt/800/600",
    desc: "RDNA 3 • 1440p ультра, 16GB, вигідна ціна.",
    specs: { "Памʼять": "16GB GDDR6", "TBP": "≈263W" },
    buy: "#"
  },
  {
    id: "gpu-rtx3050",
    title: "GeForce RTX 3050 8GB",
    category: "gpu",
    price: 8999,
    rating: 4.3,
    sku: "RTX3050-8G",
    img: "https://picsum.photos/seed/gpu3050/800/600",
    desc: "Вхід до RTX/ DLSS у бюджетному сегменті.",
    specs: { "Памʼять": "8GB GDDR6", "TBP": "≈130W" },
    buy: "#"
  },
  {
    id: "gpu-rtx4070s",
    title: "GeForce RTX 4070 SUPER 12GB",
    category: "gpu",
    price: 31999,
    rating: 4.7,
    sku: "RTX4070S-12G",
    img: "https://picsum.photos/seed/gpu4070s/800/600",
    desc: "Покращені ядра/частоти • 1440p/4K з DLSS.",
    specs: { "Памʼять": "12GB GDDR6X", "TBP": "≈220W" },
    buy: "#"
  },
  {
    id: "gpu-rx7900xt",
    title: "Radeon RX 7900 XT 20GB",
    category: "gpu",
    price: 39999,
    rating: 4.6,
    sku: "RX7900XT-20G",
    img: "https://picsum.photos/seed/gpu7900xt/800/600",
    desc: "Флагман RDNA 3 для 4K без компромісів.",
    specs: { "Памʼять": "20GB GDDR6", "TBP": "≈315W" },
    buy: "#"
  },
  {
    id: "gpu-rtx4080s",
    title: "GeForce RTX 4080 SUPER 16GB",
    category: "gpu",
    price: 49999,
    rating: 4.8,
    sku: "RTX4080S-16G",
    img: "https://picsum.photos/seed/gpu4080s/800/600",
    desc: "Преміум 4K + рейтрейсинг • DLSS 3.5.",
    specs: { "Памʼять": "16GB GDDR6X", "TBP": "≈320W" },
    buy: "#"
  },

  /* ============================
     RAM — Оперативна памʼять (10)
  ============================ */
  {
    id: "ram-ddr4-16-3200",
    title: "DDR4 16GB (2×8) 3200",
    category: "ram",
    price: 1399,
    rating: 4.7,
    sku: "DDR4-16-3200",
    img: "https://picsum.photos/seed/ram1/800/600",
    desc: "Надійний набір для масових систем AM4/LGA1200.",
    specs: { "Тип": "DDR4", "Ємність": "16GB (2×8)", "Частота": "3200" },
    buy: "#"
  },
  {
    id: "ram-ddr4-32-3200",
    title: "DDR4 32GB (2×16) 3200",
    category: "ram",
    price: 2599,
    rating: 4.8,
    sku: "DDR4-32-3200",
    img: "https://picsum.photos/seed/ram2/800/600",
    desc: "Для багатозадачності, стрімінгу, робочих задач.",
    specs: { "Тип": "DDR4", "Ємність": "32GB (2×16)", "Частота": "3200" },
    buy: "#"
  },
  {
    id: "ram-ddr5-16-5600",
    title: "DDR5 16GB (2×8) 5600",
    category: "ram",
    price: 1999,
    rating: 4.6,
    sku: "DDR5-16-5600",
    img: "https://picsum.photos/seed/ram3/800/600",
    desc: "Стартовий комплект під LGA1700/AM5.",
    specs: { "Тип": "DDR5", "Ємність": "16GB (2×8)", "Частота": "5600" },
    buy: "#"
  },
  {
    id: "ram-ddr5-32-6000",
    title: "DDR5 32GB (2×16) 6000",
    category: "ram",
    price: 3999,
    rating: 4.8,
    sku: "DDR5-32-6000",
    img: "https://picsum.photos/seed/ram4/800/600",
    desc: "Оптимальний вибір під Ryzen 7000/Intel 13-14 gen.",
    specs: { "Тип": "DDR5", "Ємність": "32GB (2×16)", "Частота": "6000" },
    buy: "#"
  },
  {
    id: "ram-ddr5-64-6000",
    title: "DDR5 64GB (2×32) 6000",
    category: "ram",
    price: 7999,
    rating: 4.9,
    sku: "DDR5-64-6000",
    img: "https://picsum.photos/seed/ram5/800/600",
    desc: "Під роботу з великими проєктами та рендер.",
    specs: { "Тип": "DDR5", "Ємність": "64GB (2×32)", "Частота": "6000" },
    buy: "#"
  },
  {
    id: "ram-ddr4-32-3600",
    title: "DDR4 32GB (2×16) 3600",
    category: "ram",
    price: 2899,
    rating: 4.7,
    sku: "DDR4-32-3600",
    img: "https://picsum.photos/seed/ram6/800/600",
    desc: "Трошки швидше за 3200 — для Ryzen 5000 саме те.",
    specs: { "Тип": "DDR4", "Ємність": "32GB (2×16)", "Частота": "3600" },
    buy: "#"
  },
  {
    id: "ram-ddr5-48-6000",
    title: "DDR5 48GB (2×24) 6000",
    category: "ram",
    price: 5899,
    rating: 4.6,
    sku: "DDR5-48-6000",
    img: "https://picsum.photos/seed/ram7/800/600",
    desc: "Нестандартний об’єм для творчих задач.",
    specs: { "Тип": "DDR5", "Ємність": "48GB (2×24)", "Частота": "6000" },
    buy: "#"
  },
  {
    id: "ram-ddr5-32-6400",
    title: "DDR5 32GB (2×16) 6400",
    category: "ram",
    price: 4499,
    rating: 4.6,
    sku: "DDR5-32-6400",
    img: "https://picsum.photos/seed/ram8/800/600",
    desc: "Оверклокерський комплект для Intel.",
    specs: { "Тип": "DDR5", "Ємність": "32GB (2×16)", "Частота": "6400" },
    buy: "#"
  },
  {
    id: "ram-ddr5-rgb-32-6000",
    title: "DDR5 32GB 6000 RGB",
    category: "ram",
    price: 4299,
    rating: 4.7,
    sku: "DDR5-32-6000-RGB",
    img: "https://picsum.photos/seed/ram9/800/600",
    desc: "З підсвіткою • XMP/EXPO профілі.",
    specs: { "Тип": "DDR5", "Ємність": "32GB", "Частота": "6000" },
    buy: "#"
  },
  {
    id: "ram-ddr4-16-3000",
    title: "DDR4 16GB (2×8) 3000",
    category: "ram",
    price: 1299,
    rating: 4.5,
    sku: "DDR4-16-3000",
    img: "https://picsum.photos/seed/ram10/800/600",
    desc: "Економ-набір для офісу/лайт-геймінгу.",
    specs: { "Тип": "DDR4", "Ємність": "16GB", "Частота": "3000" },
    buy: "#"
  },

  /* ============================
     MB — Материнські плати (10)
  ============================ */
  {
    id: "mb-b550-atx",
    title: "MSI B550 Tomahawk (ATX)",
    category: "mb",
    price: 4699,
    rating: 4.7,
    sku: "B550-TOMAHAWK",
    img: "https://picsum.photos/seed/mb1/800/600",
    desc: "Класика під Ryzen 3000/5000 • добрий VRM.",
    specs: { "Сокет": "AM4", "Форм-фактор": "ATX", "M.2": "2×", "LAN": "2.5G" },
    buy: "#"
  },
  {
    id: "mb-b450m",
    title: "ASUS PRIME B450M-A II (mATX)",
    category: "mb",
    price: 2699,
    rating: 4.4,
    sku: "PRIME-B450M-A-II",
    img: "https://picsum.photos/seed/mb2/800/600",
    desc: "Бюджет під AM4, офіс/база під апгрейд.",
    specs: { "Сокет": "AM4", "Форм-фактор": "mATX", "M.2": "1×" },
    buy: "#"
  },
  {
    id: "mb-b650",
    title: "Gigabyte B650 AORUS Elite (ATX)",
    category: "mb",
    price: 6499,
    rating: 4.6,
    sku: "B650-AORUS-ELITE",
    img: "https://picsum.photos/seed/mb3/800/600",
    desc: "Під Ryzen 7000, PCIe 5.0 для SSD.",
    specs: { "Сокет": "AM5", "Форм-фактор": "ATX", "M.2": "3×", "LAN": "2.5G" },
    buy: "#"
  },
  {
    id: "mb-x670",
    title: "ASUS TUF Gaming X670-Plus Wi-Fi",
    category: "mb",
    price: 9999,
    rating: 4.7,
    sku: "TUF-X670-PLUS-WIFI",
    img: "https://picsum.photos/seed/mb4/800/600",
    desc: "Потужний VRM, багато портів, Wi-Fi 6.",
    specs: { "Сокет": "AM5", "Форм-фактор": "ATX", "M.2": "4×", "Wi-Fi": "6" },
    buy: "#"
  },
  {
    id: "mb-z690",
    title: "MSI PRO Z690-A DDR4 (ATX)",
    category: "mb",
    price: 7999,
    rating: 4.6,
    sku: "PRO-Z690-A-DDR4",
    img: "https://picsum.photos/seed/mb5/800/600",
    desc: "Під 12-13 gen, чимало M.2 і портів.",
    specs: { "Сокет": "LGA1700", "Форм-фактор": "ATX", "M.2": "4×" },
    buy: "#"
  },
  {
    id: "mb-z790",
    title: "ASUS PRIME Z790-P Wi-Fi (ATX)",
    category: "mb",
    price: 10999,
    rating: 4.7,
    sku: "PRIME-Z790-P-WIFI",
    img: "https://picsum.photos/seed/mb6/800/600",
    desc: "Оновлена платформа для 13-14 gen.",
    specs: { "Сокет": "LGA1700", "Форм-фактор": "ATX", "M.2": "4×", "Wi-Fi": "6" },
    buy: "#"
  },
  {
    id: "mb-b760m",
    title: "Gigabyte B760M DS3H AX (mATX)",
    category: "mb",
    price: 5499,
    rating: 4.6,
    sku: "B760M-DS3H-AX",
    img: "https://picsum.photos/seed/mb7/800/600",
    desc: "B760 під 12-14 gen • Wi-Fi 6, 2.5G LAN.",
    specs: { "Сокет": "LGA1700", "Форм-фактор": "mATX", "Wi-Fi": "6" },
    buy: "#"
  },
  {
    id: "mb-h610m",
    title: "ASRock H610M-HDV/M.2 (mATX)",
    category: "mb",
    price: 2199,
    rating: 4.3,
    sku: "H610M-HDV-M2",
    img: "https://picsum.photos/seed/mb8/800/600",
    desc: "Мінімум необхідного для i3/i5 без розгону.",
    specs: { "Сокет": "LGA1700", "Форм-фактор": "mATX", "M.2": "1×" },
    buy: "#"
  },
  {
    id: "mb-b660",
    title: "MSI B660M Mortar Wi-Fi (mATX)",
    category: "mb",
    price: 4999,
    rating: 4.6,
    sku: "B660M-MORTAR-WIFI",
    img: "https://picsum.photos/seed/mb9/800/600",
    desc: "Середній клас для 12-13 gen з Wi-Fi.",
    specs: { "Сокет": "LGA1700", "Форм-фактор": "mATX", "Wi-Fi": "6" },
    buy: "#"
  },
  {
    id: "mb-a520m",
    title: "Gigabyte A520M S2H (mATX)",
    category: "mb",
    price: 1899,
    rating: 4.2,
    sku: "A520M-S2H",
    img: "https://picsum.photos/seed/mb10/800/600",
    desc: "Найдоступніша плата під Ryzen без розгону.",
    specs: { "Сокет": "AM4", "Форм-фактор": "mATX", "M.2": "1×" },
    buy: "#"
  },

  /* ============================
     STORAGE — Накопичувачі (10)
  ============================ */
  {
    id: "ssd-nvme-500-pcie3",
    title: "NVMe SSD 500GB (PCIe 3.0)",
    category: "storage",
    price: 999,
    rating: 4.7,
    sku: "NVME-500-PCIe3",
    img: "https://picsum.photos/seed/ssd1/800/600",
    desc: "До 2500/2000 MB/s • для швидкого старту.",
    specs: { "Інтерфейс": "PCIe 3.0 x4", "Форм-фактор": "M.2 2280" },
    buy: "#"
  },
  {
    id: "ssd-nvme-1tb-pcie3",
    title: "NVMe SSD 1TB (PCIe 3.0)",
    category: "storage",
    price: 1799,
    rating: 4.8,
    sku: "NVME-1TB-PCIe3",
    img: "https://picsum.photos/seed/ssd2/800/600",
    desc: "Швидко й недорого для ігор/роботи.",
    specs: { "Інтерфейс": "PCIe 3.0 x4", "Форм-фактор": "M.2 2280" },
    buy: "#"
  },
  {
    id: "ssd-nvme-1tb-pcie4",
    title: "NVMe SSD 1TB Gen4",
    category: "storage",
    price: 2399,
    rating: 4.8,
    sku: "NVME-1TB-Gen4",
    img: "https://picsum.photos/seed/ssd3/800/600",
    desc: "До 5000/4500 MB/s • краще для сучасних ігор.",
    specs: { "Інтерфейс": "PCIe 4.0 x4", "Форм-фактор": "M.2 2280" },
    buy: "#"
  },
  {
    id: "ssd-nvme-2tb-pcie4",
    title: "NVMe SSD 2TB Gen4",
    category: "storage",
    price: 4399,
    rating: 4.8,
    sku: "NVME-2TB-Gen4",
    img: "https://picsum.photos/seed/ssd4/800/600",
    desc: "Для великих бібліотек ігор та монтажу.",
    specs: { "Інтерфейс": "PCIe 4.0 x4", "Форм-фактор": "M.2 2280" },
    buy: "#"
  },
  {
    id: "ssd-sata-480",
    title: "SATA SSD 480GB",
    category: "storage",
    price: 799,
    rating: 4.6,
    sku: "SATA-SSD-480",
    img: "https://picsum.photos/seed/ssd5/800/600",
    desc: "Бюджетне прискорення старих ПК/ноутбуків.",
    specs: { "Інтерфейс": "SATA III", "Форм-фактор": "2.5\"" },
    buy: "#"
  },
  {
    id: "hdd-1tb",
    title: "HDD 1TB 7200rpm",
    category: "storage",
    price: 1499,
    rating: 4.4,
    sku: "HDD-1TB-7200",
    img: "https://picsum.photos/seed/ssd6/800/600",
    desc: "Архів/медіатека, оптимально за ціною.",
    specs: { "Інтерфейс": "SATA III", "Форм-фактор": "3.5\"" },
    buy: "#"
  },
  {
    id: "hdd-2tb",
    title: "HDD 2TB 7200rpm",
    category: "storage",
    price: 2099,
    rating: 4.5,
    sku: "HDD-2TB-7200",
    img: "https://picsum.photos/seed/ssd7/800/600",
    desc: "Більше місця для відео та ігор.",
    specs: { "Інтерфейс": "SATA III", "Форм-фактор": "3.5\"" },
    buy: "#"
  },
  {
    id: "ssd-2230-1tb",
    title: "NVMe 2230 1TB (Steam Deck)",
    category: "storage",
    price: 2799,
    rating: 4.7,
    sku: "NVME-2230-1TB",
    img: "https://picsum.photos/seed/ssd8/800/600",
    desc: "Компактний форм-фактор для портативок.",
    specs: { "Інтерфейс": "PCIe 4.0 x4", "Форм-фактор": "M.2 2230" },
    buy: "#"
  },
  {
    id: "ext-ssd-1tb",
    title: "Зовнішній SSD 1TB USB-C",
    category: "storage",
    price: 3499,
    rating: 4.7,
    sku: "EXT-SSD-1TB",
    img: "https://picsum.photos/seed/ssd9/800/600",
    desc: "Швидкий переносний накопичувач для робочих файлів.",
    specs: { "Інтерфейс": "USB-C 10Gbps", "Форм-фактор": "Портативний" },
    buy: "#"
  },
  {
    id: "ssd-nvme-2tb-pcie3",
    title: "NVMe SSD 2TB (PCIe 3.0)",
    category: "storage",
    price: 3299,
    rating: 4.7,
    sku: "NVME-2TB-PCIe3",
    img: "https://picsum.photos/seed/ssd10/800/600",
    desc: "Компроміс швидкості/ціни для великого об’єму.",
    specs: { "Інтерфейс": "PCIe 3.0 x4", "Форм-фактор": "M.2 2280" },
    buy: "#"
  },

  /* ============================
     CASE — Корпуси (10)
  ============================ */
  {
    id: "case-mesh-atx",
    title: "ATX Mesh скло + 3×120мм",
    category: "case",
    price: 2799,
    rating: 4.6,
    sku: "MESH-ATX-3FAN",
    img: "https://picsum.photos/seed/case1/800/600",
    desc: "Добра продувність, ARGB вентилятори в комплекті.",
    specs: { "Форм-фактор": "ATX", "Вентилятори": "3×120мм" },
    buy: "#"
  },
  {
    id: "case-matx-budget",
    title: "mATX бюджетний",
    category: "case",
    price: 1999,
    rating: 4.3,
    sku: "MATX-BASIC",
    img: "https://picsum.photos/seed/case2/800/600",
    desc: "Компактний корпус під офіс/бюджетні збірки.",
    specs: { "Форм-фактор": "mATX", "Довжина GPU": "до 320 мм" },
    buy: "#"
  },
  {
    id: "case-tg-rgb",
    title: "ATX скло + ARGB",
    category: "case",
    price: 3499,
    rating: 4.5,
    sku: "ATX-GLASS-ARGB",
    img: "https://picsum.photos/seed/case3/800/600",
    desc: "Загартоване скло, пилові фільтри.",
    specs: { "Форм-фактор": "ATX", "Вентилятори": "4×120мм" },
    buy: "#"
  },
  {
    id: "case-white",
    title: "ATX білий Airflow",
    category: "case",
    price: 3199,
    rating: 4.6,
    sku: "ATX-WHITE-AIR",
    img: "https://picsum.photos/seed/case4/800/600",
    desc: "Світлий мінімалізм з сіткою попереду.",
    specs: { "Форм-фактор": "ATX", "Довжина GPU": "до 380 мм" },
    buy: "#"
  },
  {
    id: "case-fractal-meshify",
    title: "Fractal Meshify C",
    category: "case",
    price: 3999,
    rating: 4.7,
    sku: "FRACTAL-MESHIFY-C",
    img: "https://picsum.photos/seed/case5/800/600",
    desc: "Іконічний дизайн, чудова вентиляція.",
    specs: { "Форм-фактор": "ATX", "Фільтри": "Повний комплект" },
    buy: "#"
  },
  {
    id: "case-nzxt-h5",
    title: "NZXT H5 Flow",
    category: "case",
    price: 4699,
    rating: 4.6,
    sku: "NZXT-H5-FLOW",
    img: "https://picsum.photos/seed/case6/800/600",
    desc: "Охайний дизайн, гарна ергономіка для складання.",
    specs: { "Форм-фактор": "ATX", "Фронт": "Mesh" },
    buy: "#"
  },
  {
    id: "case-deepcool-55",
    title: "DeepCool Matrexx 55 Mesh",
    category: "case",
    price: 2399,
    rating: 4.4,
    sku: "MATREXX-55-MESH",
    img: "https://picsum.photos/seed/case7/800/600",
    desc: "Доступний корпус з добрим потоком.",
    specs: { "Форм-фактор": "ATX" },
    buy: "#"
  },
  {
    id: "case-nr200p",
    title: "Cooler Master NR200P (Mini-ITX)",
    category: "case",
    price: 4999,
    rating: 4.8,
    sku: "NR200P",
    img: "https://picsum.photos/seed/case8/800/600",
    desc: "Компакний SFF з прозорою панеллю.",
    specs: { "Форм-фактор": "Mini-ITX", "GPU": "до 330 мм" },
    buy: "#"
  },
  {
    id: "case-p300a",
    title: "Phanteks P300A Mesh",
    category: "case",
    price: 2899,
    rating: 4.6,
    sku: "P300A",
    img: "https://picsum.photos/seed/case9/800/600",
    desc: "Чистий дизайн + відмінний повітряний потік.",
    specs: { "Форм-фактор": "ATX" },
    buy: "#"
  },
  {
    id: "case-lancool216",
    title: "Lian Li Lancool 216",
    category: "case",
    price: 5499,
    rating: 4.7,
    sku: "LANCOOL-216",
    img: "https://picsum.photos/seed/case10/800/600",
    desc: "Дві 160мм турбіни попереду, чудовий Airflow.",
    specs: { "Форм-фактор": "ATX", "Вентилятори": "2×160мм + 1×140мм" },
    buy: "#"
  },

  /* ============================
     PSU — Блоки живлення (10)
  ============================ */
  {
    id: "psu-550-bronze",
    title: "PSU 550W 80+ Bronze",
    category: "psu",
    price: 1799,
    rating: 4.5,
    sku: "PSU-550-BR",
    img: "https://picsum.photos/seed/psu1/800/600",
    desc: "Бюджет під збірки без топ-GPU.",
    specs: { "Сертифікація": "80+ Bronze", "Кабелі": "Немодульні" },
    buy: "#"
  },
  {
    id: "psu-650-gold",
    title: "PSU 650W 80+ Gold",
    category: "psu",
    price: 3199,
    rating: 4.7,
    sku: "PSU-650-GOLD",
    img: "https://picsum.photos/seed/psu2/800/600",
    desc: "Золотий стандарт під RTX 4060/4070.",
    specs: { "Сертифікація": "80+ Gold", "Кабелі": "Частково модульні" },
    buy: "#"
  },
  {
    id: "psu-750-gold",
    title: "PSU 750W 80+ Gold",
    category: "psu",
    price: 3999,
    rating: 4.8,
    sku: "PSU-750-GOLD",
    img: "https://picsum.photos/seed/psu3/800/600",
    desc: "Для потужніших GPU та апгрейду.",
    specs: { "Сертифікація": "80+ Gold", "Кабелі": "Модульні" },
    buy: "#"
  },
  {
    id: "psu-850-gold",
    title: "PSU 850W 80+ Gold",
    category: "psu",
    price: 4999,
    rating: 4.8,
    sku: "PSU-850-GOLD",
    img: "https://picsum.photos/seed/psu4/800/600",
    desc: "Запас для RTX 4080/7900XT.",
    specs: { "Сертифікація": "80+ Gold", "Кабелі": "Модульні" },
    buy: "#"
  },
  {
    id: "psu-1000-gold",
    title: "PSU 1000W 80+ Gold",
    category: "psu",
    price: 6999,
    rating: 4.7,
    sku: "PSU-1000-GOLD",
    img: "https://picsum.photos/seed/psu5/800/600",
    desc: "Для топових збірок з великим розгоном.",
    specs: { "Сертифікація": "80+ Gold", "Кабелі": "Модульні" },
    buy: "#"
  },
  {
    id: "psu-650-bronze",
    title: "PSU 650W 80+ Bronze",
    category: "psu",
    price: 2299,
    rating: 4.4,
    sku: "PSU-650-BR",
    img: "https://picsum.photos/seed/psu6/800/600",
    desc: "Недорогий варіант для мейнстріму.",
    specs: { "Сертифікація": "80+ Bronze" },
    buy: "#"
  },
  {
    id: "psu-750-platinum",
    title: "PSU 750W 80+ Platinum",
    category: "psu",
    price: 5999,
    rating: 4.8,
    sku: "PSU-750-PL",
    img: "https://picsum.photos/seed/psu7/800/600",
    desc: "Максимальна ефективність у середньому класі.",
    specs: { "Сертифікація": "80+ Platinum" },
    buy: "#"
  },
  {
    id: "psu-sfx-650-gold",
    title: "PSU SFX 650W 80+ Gold",
    category: "psu",
    price: 5299,
    rating: 4.7,
    sku: "PSU-SFX-650-G",
    img: "https://picsum.photos/seed/psu8/800/600",
    desc: "Для Mini-ITX/NR200P, компактний форм-фактор.",
    specs: { "Сертифікація": "80+ Gold", "Форм-фактор": "SFX" },
    buy: "#"
  },
  {
    id: "psu-500-bronze",
    title: "PSU 500W 80+ Bronze",
    category: "psu",
    price: 1499,
    rating: 4.3,
    sku: "PSU-500-BR",
    img: "https://picsum.photos/seed/psu9/800/600",
    desc: "Під офіс/домашній ПК без дискретної відеокарти.",
    specs: { "Сертифікація": "80+ Bronze" },
    buy: "#"
  },
  {
    id: "psu-600-gold",
    title: "PSU 600W 80+ Gold",
    category: "psu",
    price: 2899,
    rating: 4.5,
    sku: "PSU-600-G",
    img: "https://picsum.photos/seed/psu10/800/600",
    desc: "Енергоефективність і тиша за помірні гроші.",
    specs: { "Сертифікація": "80+ Gold" },
    buy: "#"
  },

  /* ============================
     COOLING — Охолодження (10)
  ============================ */
  {
    id: "cool-air-120",
    title: "Кулер баштовий 120мм (4 теплотрубки)",
    category: "cooling",
    price: 1299,
    rating: 4.6,
    sku: "AIR-120-4P",
    img: "https://picsum.photos/seed/cool1/800/600",
    desc: "Оптимум для i5/R5 без розгону.",
    specs: { "Тип": "Баштовий", "Вентилятор": "120мм PWM" },
    buy: "#"
  },
  {
    id: "cool-air-92-lp",
    title: "Низькопрофільний кулер 92мм",
    category: "cooling",
    price: 999,
    rating: 4.4,
    sku: "LP-COOL-92",
    img: "https://picsum.photos/seed/cool2/800/600",
    desc: "Для компактних корпусів/HTPC.",
    specs: { "Тип": "Low Profile", "Вентилятор": "92мм PWM" },
    buy: "#"
  },
  {
    id: "cool-aio-240",
    title: "СВО 240мм (AIO)",
    category: "cooling",
    price: 3699,
    rating: 4.6,
    sku: "AIO-240",
    img: "https://picsum.photos/seed/cool3/800/600",
    desc: "Баланс температур і шуму.",
    specs: { "Радіатор": "240мм", "Підсвітка": "ARGB" },
    buy: "#"
  },
  {
    id: "cool-aio-360",
    title: "СВО 360мм (AIO)",
    category: "cooling",
    price: 5999,
    rating: 4.7,
    sku: "AIO-360",
    img: "https://picsum.photos/seed/cool4/800/600",
    desc: "Для потужних CPU з запасом.",
    specs: { "Радіатор": "360мм", "Вентилятори": "3×120мм" },
    buy: "#"
  },
  {
    id: "cool-fan-120pwm",
    title: "Вентилятор 120мм PWM",
    category: "cooling",
    price: 299,
    rating: 4.5,
    sku: "FAN-120-PWM",
    img: "https://picsum.photos/seed/cool5/800/600",
    desc: "Тихий корпусний вентилятор.",
    specs: { "Розмір": "120×25мм", "Швидкість": "до 1500RPM" },
    buy: "#"
  },
  {
    id: "cool-fan-140pwm",
    title: "Вентилятор 140мм PWM",
    category: "cooling",
    price: 399,
    rating: 4.5,
    sku: "FAN-140-PWM",
    img: "https://picsum.photos/seed/cool6/800/600",
    desc: "Для корпусів з великим фронтом.",
    specs: { "Розмір": "140×25мм", "Швидкість": "до 1200RPM" },
    buy: "#"
  },
  {
    id: "cool-fan-argb-3pack",
    title: "Набір 3×120мм ARGB",
    category: "cooling",
    price: 899,
    rating: 4.6,
    sku: "FAN-ARGB-3",
    img: "https://picsum.photos/seed/cool7/800/600",
    desc: "Підсвітка + хаб у комплекті.",
    specs: { "Комплект": "3 вентилятори", "Інтерфейс": "ARGB 5V" },
    buy: "#"
  },
  {
    id: "cool-air-6pipes",
    title: "Баштовий кулер 120мм (6 трубок)",
    category: "cooling",
    price: 1799,
    rating: 4.7,
    sku: "AIR-120-6P",
    img: "https://picsum.photos/seed/cool8/800/600",
    desc: "Для i7/R7 з турбо-навантаженням.",
    specs: { "Тип": "Баштовий", "Трубки": "6" },
    buy: "#"
  },
  {
    id: "cool-aio-280",
    title: "СВО 280мм (AIO)",
    category: "cooling",
    price: 4799,
    rating: 4.6,
    sku: "AIO-280",
    img: "https://picsum.photos/seed/cool9/800/600",
    desc: "Тихі 140мм вертушки + добра продуктивність.",
    specs: { "Радіатор": "280мм", "Вентилятори": "2×140мм" },
    buy: "#"
  },
  {
    id: "cool-thermal-paste",
    title: "Термопаста (висока провідність)",
    category: "cooling",
    price: 199,
    rating: 4.8,
    sku: "PASTE-HIGH",
    img: "https://picsum.photos/seed/cool10/800/600",
    desc: "Стабільні температури та легке нанесення.",
    specs: { "Тип": "Паста", "Маса": "3–5 г" },
    buy: "#"
  }
];

